name: CI

# タイミングを指定
on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yarn install
        run: yarn install
      # - name: Run eslint
      #   run: yarn lint
      - name: Run Jest
        run: yarn test
