name: 'coverage'
on:
  - push
  # - pull_request
  # branches:
  #   - master
  #   - main
  #   - develop
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        package-manager: 'yarn'
        test-script: npm run test:coverage
